import AxeBuilder from '@axe-core/playwright'
import { expect, type Locator, type Page } from '@playwright/test'

/**
 * Shared helpers for the browser suite.
 *
 * Every test runs against the production build served by `vite preview`, with no
 * read API configured, so the page shows the committed `preview` fixture. Two
 * things follow from that and shape everything here.
 *
 * The fixture was scanned at a fixed instant and is regenerated by
 * `go test ./internal/snapshot -update`, so it is permanently older than the
 * machine's clock. A test that let the real clock decide would report a different
 * age, a different set of stale warnings, and different countdowns every day it
 * ran. So the clock is always given: `?now=` for a frozen instant, or Playwright's
 * own clock for the cases that must see time pass.
 *
 * And the fixture is chosen at build time, so a browser test cannot switch to the
 * `stale` fixture. It does not need to: moving the clock forward past a source
 * list's window makes the same snapshot stale, which is the code path that matters.
 *
 * The page opens on the available view, which the fixture answers with two of its
 * ten names. So a test about the table itself - every status, every countdown, the
 * longest strings, ten rows - asks for `view=all` rather than reading whatever the
 * landing view happens to hold.
 */

/** The instant the committed `preview` fixture records as its scan time. */
export const SCANNED_AT = Date.UTC(2026, 2, 1, 12, 0, 0)

export const SECOND = 1000
export const MINUTE = 60 * SECOND
export const HOUR = 60 * MINUTE
export const DAY = 24 * HOUR

/** An instant this far after the scan, written to the second as the page writes it. */
export function since(offsetMs: number): string {
  return new Date(SCANNED_AT + offsetMs).toISOString().replace(/\.\d{3}Z$/, 'Z')
}

/**
 * Opens the site at a simulated instant, defaulting to the scan itself.
 *
 * Extra parameters are appended after `now`, so a test can override the clock or
 * add filters, and the resulting link is the same one a visitor could share.
 */
export async function visit(page: Page, params: Record<string, string> = {}): Promise<void> {
  const query = new URLSearchParams({ now: since(0), ...params })
  await page.goto(`/?${query.toString()}`)
  await expect(results(page)).toBeVisible()
}

/**
 * The results region, whichever view is on show.
 *
 * It is named by the page's `<h1>`, and every view titles itself `<something> .eth
 * names`, so this is also what tells a test that the snapshot has arrived: the
 * region is not rendered until there is one.
 */
export function results(page: Page): Locator {
  return page.getByRole('region', { name: /\.eth names$/ })
}

/**
 * Opens a `<details>` by its summary, and waits until it is open.
 *
 * Two things on the page are disclosures - the extra filters and the scan details -
 * and their content is display:none until asked for. A `boundingBox()` inside a
 * closed one is `null` and a `getBoundingClientRect()` is all zeroes, so a layout
 * or contrast assertion made against a closed disclosure passes without checking
 * anything. Every test that measures or inspects that content opens it first.
 */
async function open(page: Page, name: string): Promise<void> {
  const summary = page.locator('summary').filter({ hasText: name })
  await summary.click()
  // The element the browser owns, not a class name: `open` is what actually
  // decides whether the content below has any layout.
  await expect(page.locator('details', { has: summary })).toHaveJSProperty('open', true)
}

/** Opens the source-list, sort, and status controls. */
export function openMore(page: Page): Promise<void> {
  return open(page, 'More filters')
}

/** Opens the provenance, per-list schedules, counts, lifecycle rules, and method. */
export function openDetails(page: Page): Promise<void> {
  return open(page, 'Scan details, source lists, and method')
}

const WCAG_TAGS = ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']

/**
 * Fails with the list of rule violations axe found, so the message names the rule
 * rather than only the count.
 */
export async function expectAccessible(page: Page): Promise<void> {
  const { violations } = await new AxeBuilder({ page }).withTags(WCAG_TAGS).analyze()
  expect(
    violations.map(
      (violation) =>
        `${violation.id}: ${violation.nodes.map((node) => node.target.join(' ')).join(', ')}`,
    ),
  ).toEqual([])
}

/**
 * Whether the document itself scrolls sideways.
 *
 * `documentElement.scrollWidth` is not the test. Chrome reports the widest content
 * anywhere on the page, including content inside a nested element that scrolls on
 * its own, so it reads wider than the viewport on a page that does not move at
 * all. Asking the document to scroll and seeing whether it moved is what a visitor
 * would actually experience.
 */
export function scrollsSideways(page: Page): Promise<boolean> {
  return page.evaluate(() => {
    window.scrollTo(9999, 0)
    const moved = window.scrollX > 0
    window.scrollTo(0, 0)
    return moved
  })
}

/** The query string of the address bar, including its leading `?`. */
export function searchOf(page: Page): string {
  return new URL(page.url()).search
}
